# Site settings
title: The Story of My Life
email: waldronlucas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am currently enrolled in the University of Pittsburgh and plan to pursue
  a degree in Political Science and German with a Turkish minor and possibly a
  minor in Computer Science as well. I'm all over the place, honestly.
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: larrow_lucas
github_username:  LArrowHead
author:
  name: "Lucas Waldron"
  email: "waldronlucas@gmail.com"
  #url: ""

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
